name: deploy things

on: 
  push:
    branches: 
      - main

permissions: 
  id-token: write 

jobs: 
  terraform: 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: "1.13"
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      
      - name: Init
        run: terraform init

      - name: Apply
        run: terraform apply -auto-approve